# Generated by Django 4.2.1 on 2023-09-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("username", models.CharField(max_length=50, verbose_name="username")),
                ("phone", models.CharField(max_length=11, verbose_name="phone")),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
            ],
        ),
    ]
